from pathlib import Path

BASE_PATH = Path(__file__).resolve().parent.parent

INPUTS_DIR = BASE_PATH / "inputs"
OUTPUTS_DIR = BASE_PATH / "outputs"
WEIGHTS_DIR = BASE_PATH / "weights"
DEPENDENCY_DIR = BASE_PATH / "dependency"

SVD_WEIGHTS_PATH = WEIGHTS_DIR / "stable-video-diffusion-img2vid-xt-1-1"
DEPTHCRAFTER_WEIGHTS_PATH = WEIGHTS_DIR / "DepthCrafter"
WAN_WEIGHTS_PATH = WEIGHTS_DIR / "Wan2.1-VACE-14B-diffusers"
STEREOCRAFTER_WEIGHTS_PATH = WEIGHTS_DIR / "StereoCrafter2-FP8"
VIDEO2X_PATH = DEPENDENCY_DIR / "Video2X" / "Video2X-x86_64.AppImage"

RESOURCE_SAMPLE_INTERVAL_SECONDS = 10

DEPTH_MAX_DISP = 26
DEPTH_TARGET_FPS = 15
DEPTH_MAX_RES = 768
DEPTH_WINDOW_SIZE = 49
DEPTH_OVERLAP = 10
DEPTH_DECODE_CHUNK_SIZE = 4
DEPTH_CPU_OFFLOAD = "model"

INPAINT_TILE_NUM = 2
INPAINT_FRAMES_CHUNK = 17
INPAINT_FRAMES_OVERLAP = 2
INPAINT_TRANSFORMER_DTYPE = "fp8"
INPAINT_TRANSFORMER_CPU_OFFLOAD = "none"
INPAINT_VAE_CPU_OFFLOAD = "manual"
INPAINT_SCALE = 0.5
INPAINT_INFERENCE_STEPS = 5

GREENSCREEN_ENABLED = True
GREEN_CLEANUP_ENABLED = GREENSCREEN_ENABLED and True

INTERPOLATION_TARGET_FPS = 45

UPSCALE_TARGET_WIDTH = 5120
UPSCALE_TARGET_HEIGHT = 2560
